env:
- REPORT_CARD_GITHUB_STATUS_TOKEN=$$report_card_github_status_token
- REPORT_CARD_GITHUB_REPO_TOKEN=$$report_card_github_repo_token
image: node0.10
notify:
  email:
    recipients:
    - drone@clever.com
  slack:
    on_failure: true
    on_started: false
    on_success: false
    webhook_url: $$slack_webhook
publish:
  npm:
    email: $$email
    password: $$npmdeploypassword
    username: $$npmdeployusername
    when:
      branch: master
script:
- nvm install v6.3.1
- nvm use v6.3.1
- sudo pip install -q git+https://$REPORT_CARD_GITHUB_REPO_TOKEN@github.com/Clever/report-card.git; GITHUB_API_TOKEN=$REPORT_CARD_GITHUB_STATUS_TOKEN report-card --publish || true
- npm install
- make test
